CREATE TABLE MEDICO(
    "CRM" INTEGER NOT NULL UNIQUE,
    "DATA_INICIO" VARCHAR NOT NULL,
    "ESPECIALIDADE" VARCHAR NOT NULL,
    "ID_UNIDADE" VARCHAR,
    "ID_FUNC" VARCHAR,
    PRIMARY KEY("CRM"),
    FOREIGN KEY("ID_UNIDADE") REFERENCES UNIDADE_DE_SAUDE ("ID_UNIDADE"),
    FOREIGN KEY("ID_FUNC") REFERENCES FUNCIONARIO ("ID_FUNC"),
);
CREATE TABLE CONSULTA(
    "ID_CONSULTA" INTEGER NOT NULL UNIQUE,
    "TRATAMENTO" VARCHAR NOT NULL,
    "DIAGNOSTICO" VARCHAR NOT NULL,
    "DOENCA" VARCHAR NOT NULL,
    PRIMARY KEY("ID_CONSULTA"),
);
CREATE TABLE EXAME(
    "ID_EXAME" INTEGER NOT NULL UNIQUE,
    "TIPO" VARCHAR NOT NULL,
    "RESULTADO" VARCHAR NOT NULL,
    "DATA" VARCHAR NOT NULL,
    PRIMARY KEY("ID_EXAME"),
);
CREATE TABLE PESSOA(
    "CPF" INTEGER NOT NULL UNIQUE,
    "NOME" VARCHAR NOT NULL,
    "SEXO" VARCHAR NOT NULL,
    "IDADE" VARCHAR NOT NULL,
    "ENDERECO" VARCHAR NOT NULL UNIQUE,
    "END_SECUNDARIO" VARCHAR NOT NULL,
    "TELEFONE" VARCHAR NOT NULL,
    "EMAIL" VARCHAR NOT NULL,
    PRIMARY KEY("CPF"),
);
CREATE TABLE VACINA(
    "ID_VAC" INTEGER NOT NULL UNIQUE,
    "ID_UNIDADE" VARCHAR,
    "TIPO" VARCHAR NOT NULL,
    "DATA_INICIO" VARCHAR NOT NULL,
    "DATA_FINAL" VARCHAR NOT NULL UNIQUE,
    "NUM_VACINADOS" VARCHAR NOT NULL,
    PRIMARY KEY("ID_VAC"),
    FOREIGN KEY("ID_UNIDADE") REFERENCES UNIDADE_DE_SAUDE("ID_UNIDADE"),
);
CREATE TABLE UNIDADE_DE_SAUDE(
    "ID_UNIDADE" INTEGER NOT NULL UNIQUE,
    "NOME" VARCHAR NOT NULL,
    "TIPO" VARCHAR NOT NULL,
    "TELEFONE" VARCHAR NOT NULL,
    PRIMARY KEY("ID_UNIDADE"),
);
CREATE TABLE FUNCIONARIO(
    "ID_FUNC" INTEGER NOT NULL UNIQUE,
    "CPF" VARCHAR NOT NULL,
    "REGIAO_ATUACAO" VARCHAR NOT NULL,
    "RELATORIO_DIARIO" VARCHAR NOT NULL,
    PRIMARY KEY("ID_FUNC"),
);
CREATE TABLE AGENTE_DE_SAUDE(
    "ID_FUNC" INTEGER NOT NULL UNIQUE,
    "ID_FUNC" VARCHAR,
    PRIMARY KEY("ID_FUNC"),
    FOREIGN KEY("ID_FUNC") REFERENCES FUNCIONARIO ("ID_FUNC"),
);
CREATE TABLE AGENTE_DE_PREVENCAO(
    "ID_FUNC" INTEGER NOT NULL UNIQUE,
    "ID_FUNC" VARCHAR,
    PRIMARY KEY("ID_FUNC"),
    FOREIGN KEY("ID_FUNC") REFERENCES FUNCIONARIO ("ID_FUNC"),
);
CREATE TABLE AGENTE_DE_COMBATE(
    "ID_FUNC" INTEGER NOT NULL UNIQUE,
    "ID_FUNC" VARCHAR,
    PRIMARY KEY("ID_FUNC"),
    FOREIGN KEY("ID_FUNC") REFERENCES FUNCIONARIO ("ID_FUNC"),
);   
CREATE TABLE NOTICACAO(
    "ID_NOTIFICACAO" INTEGER NOT NULL UNIQUE,
    "CPF" VARCHAR NOT NULL,
    "DESCRICAO" VARCHAR NOT NULL,
    "ID_FUNC" VARCHAR,
    "ID_UNIDADE" VARCHAR,
    "DATA_HORA" VARCHAR NOT NULL,
    PRIMARY KEY("ID_NOTIFICACAO"),
    FOREIGN KEY("ID_UNIDADE") REFERENCES UNIDADE_DE_SAUDE ("ID_UNIDADE"),
    FOREIGN KEY("ID_FUNC") REFERENCES FUNCIONARIO ("ID_FUNC"),
);
CREATE TABLE LABORATORIO(
    "ID_LAB" INTEGER NOT NULL UNIQUE,
    "ID_NOTIFICACAO" VARCHAR,
    "NOME" VARCHAR NOT NULL,
    "TELEFONE" VARCHAR NOT NULL,
    "ENDERECO" VARCHAR NOT NULL,
    PRIMARY KEY("ID_LAB"),
    FOREIGN KEY("ID_NOTIFICACAO") REFERENCES FUNCIONARIO ("ID_NOTIFICACAO"),
);
